apiVersion: v1
kind: Service
metadata:
  name: whatsappclone-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: whatsappclone
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080