on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: testwhatsappcloneacr.azurecr.io
        username: ${{ secrets.acr_testwhatsappcloneacr_username }}
        password: ${{ secrets.acr_testwhatsappcloneacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t testwhatsappcloneacr.azurecr.io/testwhatsappclone:${{ github.sha }}
        docker push testwhatsappcloneacr.azurecr.io/testwhatsappclone:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_testwhatsappclone_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep testwhatsappclone3209 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace testwhatsappclone3209`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testwhatsappclone3209
        container-registry-url: testwhatsappcloneacr.azurecr.io
        container-registry-username: ${{ secrets.acr_testwhatsappcloneacr_username }}
        container-registry-password: ${{ secrets.acr_testwhatsappcloneacr_password }}
        secret-name: testwhatsappdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: testwhatsappclone3209
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          testwhatsappcloneacr.azurecr.io/testwhatsappclone:${{ github.sha }}
        imagepullsecrets: |
          testwhatsappdockerauth